create table `youku_user` (
  `id` int(10) unsigned not null auto_increment comment 'id',
  `y_id` varchar(30) not null comment '优酷id',
  `name` varchar(200) not null comment '用户名',
  `link` varchar(100) not null comment '空间链接',
  `avatar` varchar(200) default null comment '头像链接',
  `avatar_large` varchar(200) default null comment '大头像链接',
  `gender` varchar(10) not null default 'u' comment '性别 男：m 女：f 未知：u',
  `description` varchar(500) default null comment '描述',
  `regist_time` datetime not null comment '注册时间',
  `videos_count` int(10) unsigned not null comment '总视频数',
  `playlists_count` int(10) unsigned not null comment '总专辑数',
  `favorites_count` int(10) unsigned not null comment '总收藏视频数',
  `followers_count` int(10) unsigned not null comment '粉丝数',
  `following_count` int(10) unsigned not null comment '关注数',
  `statuses_count` int(10) unsigned not null comment '动态数',
  `subscribe_count` int(10) unsigned not null comment '被订阅数',
  `vv_count` int(10) unsigned not null comment '总视频播放数',
  `follower` char(1) default null comment '未知 0 false, 1 true',
  `following` char(1) default null comment '未知 0 false, 1 true',
  `is_share` char(1) default null comment '未知 0 false, 1 true',
  `last_update` timestamp not null default current_timestamp on update current_timestamp comment '最后更新时间',
  primary key (`id`),
  key `user_index` (`y_id`)
) engine=innodb default charset=utf8;

create table `youku_video` (
  `id` int(10) unsigned not null auto_increment comment 'id',
  `user_id` int(10) unsigned not null comment '用户id',
  `y_id` varchar(30) not null comment '优酷id',
  `playlist_id` int(10) unsigned default null comment '专辑id',
  `title` varchar(200) not null comment '标题',
  `category` varchar(50) default '' comment '分类',
  `link` varchar(100) not null comment '链接',
  `thumbnail` varchar(200) not null comment '截图链接',
  `published` datetime not null comment '发布时间',
  `duration` decimal(10,0) not null comment '视频时长，单位：秒',
  `view_count` int(10) unsigned not null comment '观看数',
  `comment_count` int(10) unsigned not null comment '评论数',
  `up_count` int(10) unsigned not null comment '被顶数',
  `down_count` int(10) unsigned not null comment '被踩数',
  `favorite_count` int(10) unsigned not null comment '被收藏数',
  `public_type` varchar(20) not null default 'all' comment '公开类型 all: 公开 friend: 仅好友观看 password: 输入密码观看',
  `state` varchar(20) not null default 'normal' comment '视频状态 normal: 正常 encoding: 转码中 fail: 转码失败 in_review: 审核中 blocked: 已屏蔽',
  `streamtypes` varchar(50) not null comment '视频格式 flvhd flv 3gphd 3gp hd hd2',
  `operation_limit` varchar(50) not null comment 'comment_disabled: 禁评论 download_disabled: 禁下载',
  `last_update` timestamp not null default current_timestamp on update current_timestamp comment '最后更新时间',
  primary key (`id`),
  unique key `u_vedio_id` (`y_id`),
  key `user_index` (`user_id`)
) engine=innodb default charset=utf8;

create table `youku_playlist` (
  `id` int(10) unsigned not null auto_increment comment 'id',
  `user_id` int(10) unsigned not null comment '用户id',
  `y_id` varchar(30) not null comment '优酷id',
  `name` varchar(100) not null comment '专辑标题',
  `link` varchar(100) not null comment '专辑链接',
  `play_link` varchar(100) default null comment '专辑播放链接',
  `thumbnail` varchar(200) not null comment '专辑截图链接',
  `published` datetime not null comment '发布时间',
  `user` varchar(200) not null comment '发布用户对象',
  `duration` decimal(10,0) not null comment '专辑总时长，单位：秒',
  `view_count` int(10) unsigned not null comment '专辑总播放数',
  `video_count` int(10) unsigned not null comment '专辑视频数量',
  `last_update` timestamp not null default current_timestamp on update current_timestamp comment '最后更新时间',
  primary key (`id`),
  key `user_index` (`user_id`)
) engine=innodb default charset=utf8;