package com.mr.hualvtu.entity;

import com.mr.hualvtu.common.BaseEntity;

import java.util.Date;

public class Album extends BaseEntity {
	private static final long serialVersionUID = -4712613531097849052L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album.dest_id
     *
     * @mbggenerated
     */
    private Integer destId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album.poi_id
     *
     * @mbggenerated
     */
    private Integer poiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album.title_img
     *
     * @mbggenerated
     */
    private String titleImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album.up_count
     *
     * @mbggenerated
     */
    private Integer upCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album.view_count
     *
     * @mbggenerated
     */
    private Integer viewCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album.comment_count
     *
     * @mbggenerated
     */
    private Integer commentCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album.music_name
     *
     * @mbggenerated
     */
    private String musicName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album.music_url
     *
     * @mbggenerated
     */
    private String musicUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album.last_updated
     *
     * @mbggenerated
     */
    private Date lastUpdated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album.id
     *
     * @return the value of album.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album.id
     *
     * @param id the value for album.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album.user_id
     *
     * @return the value of album.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album.user_id
     *
     * @param userId the value for album.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album.dest_id
     *
     * @return the value of album.dest_id
     *
     * @mbggenerated
     */
    public Integer getDestId() {
        return destId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album.dest_id
     *
     * @param destId the value for album.dest_id
     *
     * @mbggenerated
     */
    public void setDestId(Integer destId) {
        this.destId = destId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album.poi_id
     *
     * @return the value of album.poi_id
     *
     * @mbggenerated
     */
    public Integer getPoiId() {
        return poiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album.poi_id
     *
     * @param poiId the value for album.poi_id
     *
     * @mbggenerated
     */
    public void setPoiId(Integer poiId) {
        this.poiId = poiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album.name
     *
     * @return the value of album.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album.name
     *
     * @param name the value for album.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album.title_img
     *
     * @return the value of album.title_img
     *
     * @mbggenerated
     */
    public String getTitleImg() {
        return titleImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album.title_img
     *
     * @param titleImg the value for album.title_img
     *
     * @mbggenerated
     */
    public void setTitleImg(String titleImg) {
        this.titleImg = titleImg == null ? null : titleImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album.create_date
     *
     * @return the value of album.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album.create_date
     *
     * @param createDate the value for album.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album.up_count
     *
     * @return the value of album.up_count
     *
     * @mbggenerated
     */
    public Integer getUpCount() {
        return upCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album.up_count
     *
     * @param upCount the value for album.up_count
     *
     * @mbggenerated
     */
    public void setUpCount(Integer upCount) {
        this.upCount = upCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album.view_count
     *
     * @return the value of album.view_count
     *
     * @mbggenerated
     */
    public Integer getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album.view_count
     *
     * @param viewCount the value for album.view_count
     *
     * @mbggenerated
     */
    public void setViewCount(Integer viewCount) {
        this.viewCount = viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album.comment_count
     *
     * @return the value of album.comment_count
     *
     * @mbggenerated
     */
    public Integer getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album.comment_count
     *
     * @param commentCount the value for album.comment_count
     *
     * @mbggenerated
     */
    public void setCommentCount(Integer commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album.music_name
     *
     * @return the value of album.music_name
     *
     * @mbggenerated
     */
    public String getMusicName() {
        return musicName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album.music_name
     *
     * @param musicName the value for album.music_name
     *
     * @mbggenerated
     */
    public void setMusicName(String musicName) {
        this.musicName = musicName == null ? null : musicName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album.music_url
     *
     * @return the value of album.music_url
     *
     * @mbggenerated
     */
    public String getMusicUrl() {
        return musicUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album.music_url
     *
     * @param musicUrl the value for album.music_url
     *
     * @mbggenerated
     */
    public void setMusicUrl(String musicUrl) {
        this.musicUrl = musicUrl == null ? null : musicUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album.last_updated
     *
     * @return the value of album.last_updated
     *
     * @mbggenerated
     */
    public Date getLastUpdated() {
        return lastUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album.last_updated
     *
     * @param lastUpdated the value for album.last_updated
     *
     * @mbggenerated
     */
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }
}