package com.mr.hualvtu.entity;

import com.mr.hualvtu.common.BaseEntity;

import java.util.List;

public class Country extends BaseEntity {
	private static final long serialVersionUID = 5707977069577253678L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.land_id
     *
     * @mbggenerated
     */
    private Integer landId;

    private List<Dest> destList;

    public List<Dest> getDestList() {
        return destList;
    }

    public void setDestList(List<Dest> destList) {
        this.destList = destList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.id
     *
     * @return the value of country.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.id
     *
     * @param id the value for country.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.name
     *
     * @return the value of country.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.name
     *
     * @param name the value for country.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.land_id
     *
     * @return the value of country.land_id
     *
     * @mbggenerated
     */
    public Integer getLandId() {
        return landId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.land_id
     *
     * @param landId the value for country.land_id
     *
     * @mbggenerated
     */
    public void setLandId(Integer landId) {
        this.landId = landId;
    }
}