package com.mr.hualvtu.entity;

import com.mr.hualvtu.common.BaseEntity;

import java.util.Date;
import java.util.List;

public class Dest extends BaseEntity {
	private static final long serialVersionUID = -7361235268289171780L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dest.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dest.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dest.country_id
     *
     * @mbggenerated
     */
    private Integer countryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dest.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dest.title_album_id
     *
     * @mbggenerated
     */
    private Integer titleAlbumId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dest.last_updated
     *
     * @mbggenerated
     */
    private Date lastUpdated;

    private List<Poi> poiList;

    public List<Poi> getPoiList() {
        return poiList;
    }

    public void setPoiList(List<Poi> poiList) {
        this.poiList = poiList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dest.id
     *
     * @return the value of dest.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dest.id
     *
     * @param id the value for dest.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dest.name
     *
     * @return the value of dest.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dest.name
     *
     * @param name the value for dest.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dest.country_id
     *
     * @return the value of dest.country_id
     *
     * @mbggenerated
     */
    public Integer getCountryId() {
        return countryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dest.country_id
     *
     * @param countryId the value for dest.country_id
     *
     * @mbggenerated
     */
    public void setCountryId(Integer countryId) {
        this.countryId = countryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dest.description
     *
     * @return the value of dest.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dest.description
     *
     * @param description the value for dest.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dest.title_album_id
     *
     * @return the value of dest.title_album_id
     *
     * @mbggenerated
     */
    public Integer getTitleAlbumId() {
        return titleAlbumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dest.title_album_id
     *
     * @param titleAlbumId the value for dest.title_album_id
     *
     * @mbggenerated
     */
    public void setTitleAlbumId(Integer titleAlbumId) {
        this.titleAlbumId = titleAlbumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dest.last_updated
     *
     * @return the value of dest.last_updated
     *
     * @mbggenerated
     */
    public Date getLastUpdated() {
        return lastUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dest.last_updated
     *
     * @param lastUpdated the value for dest.last_updated
     *
     * @mbggenerated
     */
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }
}