package com.mr.hualvtu.entity;

public class Imgs {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imgs.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imgs.album_id
     *
     * @mbggenerated
     */
    private Integer albumId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imgs.zip_url
     *
     * @mbggenerated
     */
    private String zipUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imgs.real_url
     *
     * @mbggenerated
     */
    private String realUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imgs.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imgs.id
     *
     * @return the value of imgs.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imgs.id
     *
     * @param id the value for imgs.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imgs.album_id
     *
     * @return the value of imgs.album_id
     *
     * @mbggenerated
     */
    public Integer getAlbumId() {
        return albumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imgs.album_id
     *
     * @param albumId the value for imgs.album_id
     *
     * @mbggenerated
     */
    public void setAlbumId(Integer albumId) {
        this.albumId = albumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imgs.zip_url
     *
     * @return the value of imgs.zip_url
     *
     * @mbggenerated
     */
    public String getZipUrl() {
        return zipUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imgs.zip_url
     *
     * @param zipUrl the value for imgs.zip_url
     *
     * @mbggenerated
     */
    public void setZipUrl(String zipUrl) {
        this.zipUrl = zipUrl == null ? null : zipUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imgs.real_url
     *
     * @return the value of imgs.real_url
     *
     * @mbggenerated
     */
    public String getRealUrl() {
        return realUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imgs.real_url
     *
     * @param realUrl the value for imgs.real_url
     *
     * @mbggenerated
     */
    public void setRealUrl(String realUrl) {
        this.realUrl = realUrl == null ? null : realUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imgs.description
     *
     * @return the value of imgs.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imgs.description
     *
     * @param description the value for imgs.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}