package com.mr.hualvtu.entity;

import com.mr.hualvtu.common.BaseEntity;

import java.util.List;

public class Land extends BaseEntity {
	private static final long serialVersionUID = 4334868127799611166L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column land.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column land.name
     *
     * @mbggenerated
     */
    private String name;

    public List<Country> getCountryList() {
        return countryList;
    }

    public void setCountryList(List<Country> countryList) {
        this.countryList = countryList;
    }

    private List<Country> countryList;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column land.id
     *
     * @return the value of land.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column land.id
     *
     * @param id the value for land.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column land.name
     *
     * @return the value of land.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column land.name
     *
     * @param name the value for land.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}