package com.mr.hualvtu.entity;

import com.mr.hualvtu.common.BaseEntity;

import java.util.Date;

public class Poi extends BaseEntity {
	private static final long serialVersionUID = -5364107029859225405L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poi.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poi.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poi.dest_id
     *
     * @mbggenerated
     */
    private Integer destId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poi.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poi.last_updated
     *
     * @mbggenerated
     */
    private Date lastUpdated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poi.id
     *
     * @return the value of poi.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poi.id
     *
     * @param id the value for poi.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poi.name
     *
     * @return the value of poi.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poi.name
     *
     * @param name the value for poi.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poi.dest_id
     *
     * @return the value of poi.dest_id
     *
     * @mbggenerated
     */
    public Integer getDestId() {
        return destId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poi.dest_id
     *
     * @param destId the value for poi.dest_id
     *
     * @mbggenerated
     */
    public void setDestId(Integer destId) {
        this.destId = destId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poi.description
     *
     * @return the value of poi.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poi.description
     *
     * @param description the value for poi.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poi.last_updated
     *
     * @return the value of poi.last_updated
     *
     * @mbggenerated
     */
    public Date getLastUpdated() {
        return lastUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poi.last_updated
     *
     * @param lastUpdated the value for poi.last_updated
     *
     * @mbggenerated
     */
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }
}